# Generated by Django 3.2.17 on 2023-02-14 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectsapp', '0005_projectreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_Image',
            field=models.ImageField(default=0, upload_to='media/Projects/%y/%m/%d'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('replayId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.replay')),
            ],
        ),
    ]
