# Generated by Django 3.2.17 on 2023-02-14 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0008_projectrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrating',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
