# Generated by Django 4.1.6 on 2023-02-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0002_projectpicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectPicture',
        ),
    ]
